//
//  JobAttestation.swift
//  Axon
//
//  Axon's cryptographic signature for sub-agent job operations.
//  The attestation is the "soul" of the job - no valid signature, no execution.
//

import Foundation
import Combine

// MARK: - Job Attestation

/// Axon's cryptographic attestation for sub-agent job operations.
///
/// **Architectural Commandment #1**: The attestation is not a log entry—it is the
/// cryptographic gatekeeper. No valid signature = no execution.
struct JobAttestation: Codable, Identifiable, Equatable, Sendable {
    let id: String
    let jobId: String
    let type: AttestationType
    let timestamp: Date

    // MARK: - Axon's Reasoning

    /// Natural language reasoning for this attestation
    let reasoning: String

    /// The decision being attested
    let decision: JobAttestationDecision

    // MARK: - Cryptographic Proof

    /// HMAC-SHA256 signature generated by SovereigntyService.generateSignature()
    /// Computed over: jobId + type + timestamp + stateHash
    let signature: String

    /// Hash of the state at attestation time
    let stateHash: String

    // MARK: - Context

    /// Which model generated this attestation (for audit)
    let modelId: String

    /// Active covenant ID at attestation time
    let covenantId: String?

    /// Conversation ID where this attestation was generated
    let conversationId: String?

    // MARK: - Factory Method

    /// Create a new attestation with cryptographic signature.
    ///
    /// - Parameters:
    ///   - jobId: The job being attested
    ///   - type: Type of attestation (approval, completion, termination, etc.)
    ///   - reasoning: Natural language explanation
    ///   - decision: The decision being made
    ///   - modelId: Which model generated this attestation
    ///   - covenantId: Active covenant (if any)
    ///   - conversationId: Conversation context (if any)
    ///   - signatureGenerator: Function that generates HMAC-SHA256 signature (from SovereigntyService)
    static func create(
        jobId: String,
        type: AttestationType,
        reasoning: String,
        decision: JobAttestationDecision,
        modelId: String,
        covenantId: String?,
        conversationId: String? = nil,
        signatureGenerator: (String) -> String
    ) -> JobAttestation {
        let id = UUID().uuidString
        let timestamp = Date()

        // State hash combines job context
        let stateHash = "\(jobId):\(type.rawValue):\(timestamp.timeIntervalSince1970)"

        // Generate cryptographic signature
        let signatureData = "\(id):\(jobId):\(type.rawValue):\(timestamp.timeIntervalSince1970):\(stateHash)"
        let signature = signatureGenerator(signatureData)

        return JobAttestation(
            id: id,
            jobId: jobId,
            type: type,
            timestamp: timestamp,
            reasoning: reasoning,
            decision: decision,
            signature: signature,
            stateHash: stateHash,
            modelId: modelId,
            covenantId: covenantId,
            conversationId: conversationId
        )
    }

    // MARK: - Verification

    /// Verify that this attestation's signature is valid.
    ///
    /// - Parameter signatureGenerator: The same signature generator used at creation time
    /// - Returns: true if signature matches, false if tampered
    func verify(signatureGenerator: (String) -> String) -> Bool {
        let expectedSignatureData = "\(id):\(jobId):\(type.rawValue):\(timestamp.timeIntervalSince1970):\(stateHash)"
        let expectedSignature = signatureGenerator(expectedSignatureData)
        return signature == expectedSignature
    }

    // MARK: - Display Helpers

    var displaySummary: String {
        "\(type.displayName): \(reasoning.prefix(100))"
    }

    var shortId: String {
        String(id.prefix(8))
    }
}

// MARK: - Attestation Type

/// Types of attestations Axon can issue for sub-agent jobs.
enum AttestationType: String, Codable, CaseIterable, Sendable {
    /// Axon approves a proposed job to execute
    case approval

    /// Axon accepts the job's result
    case completion

    /// Axon terminates a job (with reason)
    case termination

    /// Axon rejects a job proposal
    case rejection

    /// Axon provides clarification to a sub-agent's question
    case clarification

    var displayName: String {
        switch self {
        case .approval: return "Approval"
        case .completion: return "Completion"
        case .termination: return "Termination"
        case .rejection: return "Rejection"
        case .clarification: return "Clarification"
        }
    }

    var icon: String {
        switch self {
        case .approval: return "checkmark.seal.fill"
        case .completion: return "flag.checkered"
        case .termination: return "stop.fill"
        case .rejection: return "xmark.seal.fill"
        case .clarification: return "text.bubble"
        }
    }

    /// Whether this attestation type requires the job to be in a specific state
    var requiredJobState: SubAgentJobState? {
        switch self {
        case .approval: return .proposed
        case .completion: return nil  // Can complete from .completed or .awaitingInput
        case .termination: return nil  // Can terminate from any non-terminal state
        case .rejection: return .proposed
        case .clarification: return .awaitingInput
        }
    }

    /// The state the job transitions to after this attestation
    var resultingJobState: SubAgentJobState? {
        switch self {
        case .approval: return .approved
        case .completion: return nil  // Doesn't change state, just seals the silo
        case .termination: return .terminated
        case .rejection: return .rejected
        case .clarification: return .approved  // Ready to re-run
        }
    }
}

// MARK: - Job Attestation Decision

/// The decision being attested for a sub-agent job.
enum JobAttestationDecision: String, Codable, Sendable {
    case consent             // Approved/accepted
    case consentWithCaveats  // Approved with conditions
    case decline             // Rejected/terminated
    case requestInfo         // Need more information (for clarification)

    var didConsent: Bool {
        self == .consent || self == .consentWithCaveats
    }

    var displayName: String {
        switch self {
        case .consent: return "Approved"
        case .consentWithCaveats: return "Approved with Conditions"
        case .decline: return "Declined"
        case .requestInfo: return "Needs Information"
        }
    }

    var icon: String {
        switch self {
        case .consent: return "checkmark.circle.fill"
        case .consentWithCaveats: return "checkmark.circle.badge.questionmark"
        case .decline: return "xmark.circle.fill"
        case .requestInfo: return "questionmark.circle"
        }
    }
}

// MARK: - Attestation Chain

/// A chain of attestations for a job, providing full audit trail.
struct AttestationChain: Codable, Equatable, Sendable {
    let jobId: String
    var attestations: [JobAttestation]

    var approval: JobAttestation? {
        attestations.first { $0.type == .approval }
    }

    var completion: JobAttestation? {
        attestations.first { $0.type == .completion }
    }

    var termination: JobAttestation? {
        attestations.first { $0.type == .termination }
    }

    var clarifications: [JobAttestation] {
        attestations.filter { $0.type == .clarification }
    }

    var isFullyAttested: Bool {
        approval != nil && (completion != nil || termination != nil)
    }

    init(jobId: String) {
        self.jobId = jobId
        self.attestations = []
    }

    mutating func add(_ attestation: JobAttestation) {
        attestations.append(attestation)
    }

    /// Verify all attestations in the chain
    func verifyAll(signatureGenerator: (String) -> String) -> Bool {
        attestations.allSatisfy { $0.verify(signatureGenerator: signatureGenerator) }
    }
}
